defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: default

title: JARVIS
subtitle: JARVIS at GNU

# Side Menu Links
menu:
  - text: JARVIS?
    link: /
    icon: ""

  - text: 알고리즘 STUDY
    link: /skills-and-offers
    icon: ""

  - text: 프로젝트 진행
    link: /contact
    icon: ""

  - text: 실리콘밸리 프로그램
    link: /resume
    icon: ""

# Socialmedia Icons
social_icons:
  - name: linkedin    //
    link: https://www.linkedin.com/christianezeani
    icon: fab fa-linkedin

  - name: github
    link: https://github.com/JARVIS-GNU
    icon: fab fa-github-square

  - name: facebook  //수정해야
    link: https://www.facebook.com/christian.ezeani.cyb
    icon: fab fa-facebook-square

  - name: twitter   //수정해야
    link: https://www.twitter.com/christianezeani
    icon: fab fa-twitter


    
